[package]
name = "bsize"
version = "0.1.0"
edition = "2018"
authors = ["myl7 <myl@myl.moe>"]
license = "MIT"

[lib]
crate-type = ["staticlib"]

[dependencies]
antlr-rust = "=0.2"
num-traits = "0.2"
num-derive = "0.3"
